
select * from appointment;

desc appointment;

Alter table  appointment
Modify Column Date Date;


-- Which doctors have the most patient appointments per month?

select
d.DoctorName,
month(ap.Date) as month,
count(ap.AppointmentID) as appointment_count
from
appointment ap 
join doctor d on ap.DoctorID=d.DoctorID
group by 1,2
order by appointment_count desc;

-- Which specialties are most in demand based on appointment count?

select
d.Specialization,
count(ap.AppointmentID) as appointment_count
from appointment ap
join Doctor d on ap.DoctorID=d.DoctorID
group by 1
order by appointment_count desc;

-- With Time Analysis

select
    d.Specialization AS specialty,
    YEAR(ap.Date) AS year,
    COUNT(ap.AppointmentID) AS appointment_count,
    RANK() OVER (PARTITION BY YEAR(ap.Date) ORDER BY COUNT(ap.AppointmentID) DESC) AS specialty_rank
from
    appointment ap 
    join Doctor d on ap.DoctorID = d.DoctorID
group by
    d.Specialization,
    YEAR(ap.Date)
order by
    year DESC,
    appointment_count DESC;


-- What is the average patient load per doctor per week?

select
d.DoctorName,
count(distinct ap.patientID) as total_patient,
count(distinct week(ap.Date)) as weeks_worked,
round(count(distinct ap.patientID)/count(distinct week(ap.Date)),2) as average_patient_per_week
from appointment ap
join doctor d on ap.DoctorID=d.DoctorID
group by 1
order by average_patient_per_week desc;

-- How many procedures does each doctor perform on average per month?

select
d.DoctorName,
count(mp.ProcedureID) as total_procedure,
count(distinct mp.ProcedureID)/count(distinct month(ap.date)) as average_procedure_per_month
from doctor d 
join appointment ap on d.DoctorID=ap.DoctorID
join medical_procedure mp on ap.AppointmentID=mp.AppointmentID
group by 1
order by average_procedure_per_month desc;

-- What is the average billing amount per procedure or appointment?

select
mp.ProcedureName,
count(distinct mp.ProcedureID) as total_procedures,
sum(b.amount)/count(distinct mp.ProcedureID) as average_billing_amount_per_procedure
from medical_procedure mp 
join appointment ap on mp.AppointmentID=ap.AppointmentID
join billing b on ap.PatientID=b.PatientID
group by 1
order by average_billing_amount_per_procedure desc;

-- Which department generates the highest revenue?

select
d.Specialization,
sum(b.amount) as total_revenue
from doctor d 
join appointment ap on d.DoctorID=ap.DoctorID
join billing b on ap.PatientID=b.PatientID
group by 1
order by total_revenue
limit 1;

-- What are the most frequently performed procedures?

select 
ProcedureName,count(*) as no_procedure_performed
from medical_procedure
group by 1
order by no_procedure_performed desc;

-- What is the average cost per procedure across departments?

select
d.Specialization as Department,
count(mp.ProcedureID) as total_procedure,
sum(b.amount)/count(mp.ProcedureId) as average_cost_per_prodecure
from doctor d
join appointment ap on d.DoctorID=ap.DoctorID
join billing b on ap.PatientID=b.PatientID
join medical_procedure mp on ap.AppointmentID=mp.AppointmentID
group by 1
order by average_cost_per_prodecure desc;

-- Are there patients undergoing repeated procedures? If yes, how frequently?

select 
ap.patientID,
mp.ProcedureName,
count(mp.AppointmentId) as ProcedureCount
from appointment ap 
join medical_procedure mp on ap.AppointmentID=mp.AppointmentID
group by 1,2
having count(mp.AppointmentId)>1
order by ProcedureCount desc;

-- What is the total revenue generated by each doctor?

With doctorRevenue as(
select
d.DoctorName,
sum(b.Amount) as total_revenue
from doctor d 
join appointment ap on D.doctorID=ap.DoctorID
join billing b on ap.PatientID=b.PatientID
group by 1
)
select * from doctorRevenue
order by total_revenue desc
limit 5;

